progress updates to initial scripting

diff --git a/_run_melseq b/_run_melseq
--- a/_run_melseq
+++ b/_run_melseq
@@ -34,7 +34,7 @@ files to process, or remove it so that the data folder is re-scanned for files t
          fi
       fi
 
-      if [ -f $OUT_ROOT/sample_info.txt ]; then
+      if [[ ( -f $OUT_ROOT/sample_info.txt ) && ( $ANALYSIS == "demultiplex" ) ]]; then
          echo "will use the following sample info . . . (press Enter/Return for a list - then press space bar to page through listing)"
          read answer
          more $OUT_ROOT/sample_info.txt
@@ -57,14 +57,20 @@ sample info , or remove it so that it is re-extracted, and try again"
 finding files to process..."
          # see if DATASET is a folder 
          if [ -d $DATASET ]; then 
-            if [[ ( $ANALYSIS == "all" ) ( $ANALYSIS == "demultiplex" ) || ( $ANALYSIS == "trim" ) ]]; then
+            if [[ ( $ANALYSIS == "all" ) || ( $ANALYSIS == "demultiplex" ) || ( $ANALYSIS == "trim" ) ]]; then
                ls $DATASET/*.fastq.gz $DATASET/*.fastq > $OUT_ROOT/input_file_list.txt
                if [ $? != 0 ]; then
                   echo "sorry could not find any data in $DATASEQ , for $ANALYSIS"
                   exit 1
-               if
-            elif [ some_other_stuff ];  ############ add file find for other analysis types
-               echo "tba !"
+               fi
+            elif [ $ANALYSIS == "blast"  ]; then 
+               set -x
+               ls $DATASET/*.fasta $DATASET/*.fa > $OUT_ROOT/input_file_list.txt
+               set +x
+               if [ $? != 0 ]; then
+                  echo "sorry could not find any data in $DATASEQ , for $ANALYSIS"
+                  exit 1
+               fi
             fi
          else
             # assume its a hiseq library name 
@@ -74,11 +80,23 @@ finding files to process..."
                exit 1
             fi
          fi
+
+         echo "will process the following files: . . . (press Enter/Return for a list - then press space bar to page through listing)"
+         read answer
+         more $OUT_ROOT/input_file_list.txt
+         echo "OK ? (default = y)"
+         read_answer_with_default y
+         if [ $answer != "y" ]; then
+            echo "
+ok quitting - you can edit the file $OUT_ROOT/input_file_list.txt in order to customise the
+files to process, or remove it so that the data folder is re-scanned for files to process, and try again"
+            exit 1
+         fi
       fi
 
       # we have files to process
-      # try getting the keyfile if not there
-      if [ ! -f $OUT_ROOT/sample_info.txt ]; then
+      # try getting the keyfile if not there and we need it 
+      if [[ ( ! -f $OUT_ROOT/sample_info.txt ) && ( $ANALYSIS == "demultiplex" ) ]]; then
          echo "getting keyfile..."
          set -x
          $GBS_PRISM_BIN/listDBKeyfile.sh  -s $DATASET -t gbsx  > $OUT_ROOT/sample_info.txt
@@ -86,36 +104,27 @@ finding files to process..."
             rm -f OUT_ROOT/sample_info.txt >/dev/null 2>&1
          fi
          set +x 
-      fi
-      echo "will process the following files: . . . (press Enter/Return for a list - then press space bar to page through listing)"
-      read answer
-      more $OUT_ROOT/input_file_list.txt
-      echo "OK ? (default = y)"
-      read_answer_with_default y
-      if [ $answer != "y" ]; then
-         echo "
-ok quitting - you can edit the file $OUT_ROOT/input_file_list.txt in order to customise the
-files to process, or remove it so that the data folder is re-scanned for files to process, and try again"
-            exit 1
-      fi
-      if [ ! -f $OUT_ROOT/sample_info.txt ]; then
-         echo "was unable to get keyfile for this run - please create $OUT_ROOT/sample_info.txt, containing sample barcode info, and try again"
-         exit 1
-      else
-         echo "will use the following sample info . . . (press Enter/Return for a list - then press space bar to page through listing)"
-         read answer
-         more $OUT_ROOT/sample_info.txt
-         echo "OK ? (default = y)"
-         read_answer_with_default y
-         if [ $answer != "y" ]; then
-            echo "
-ok quitting - you can edit the file $OUT_ROOT/sample_info.txt in order to customise the
-sample info , or remove it so that it is re-extracted, and try again"
+         if [ ! -f $OUT_ROOT/sample_info.txt ]; then
+            echo "was unable to get keyfile for this run - please create $OUT_ROOT/sample_info.txt, containing sample barcode info, and try again"
             exit 1
          else
-            break
+            echo "will use the following sample info . . . (press Enter/Return for a list - then press space bar to page through listing)"
+            read answer
+            more $OUT_ROOT/sample_info.txt
+            echo "OK ? (default = y)"
+            read_answer_with_default y
+            if [ $answer != "y" ]; then
+               echo "
+ok quitting - you can edit the file $OUT_ROOT/sample_info.txt in order to customise the
+sample info , or remove it so that it is re-extracted, and try again"
+               exit 1
+            else
+               break
+            fi
          fi
       fi
+
+      break
    done
 }
 
@@ -206,13 +215,13 @@ should this run be queued on the compute cluster ? (y/n, default=y. If n, will b
    while [ 1 ] ; do
       ANALYSIS=all
       echo "
-please give which analysis you want (all, demultiplex, trim, format, blast, summarise, kmer_analysis, clean) (or just press enter to all)  
-(the default of all, will demultiplex, then trim, then reformat as fasta, run the blast, summarise blast results and do a kmer_analysis )
+please give which analysis you want to start from (demultiplex, trim, format, blast, summarise, kmer_analysis, clean) (or just press enter to start from demultiplex)  
+(run_melseq will attempt to run te starting step and all steps after that )
 "
       read_answer_with_default all
       ANALYSIS=$answer
 
-      if [[ ( $ANALYSIS != "all" )  && ( $ANALYSIS != "demultiplex" ) && ( $ANALYSIS != "trim" ) && ( $ANALYSIS != "format" ) && ( $ANALYSIS != "blast" ) && ( $ANALYSIS != "kmer_analysis" ) && ( $ANALYSIS != "summarise" )  ]] ; then
+      if [[ ( $ANALYSIS != "demultiplex" ) && ( $ANALYSIS != "trim" ) && ( $ANALYSIS != "format" ) && ( $ANALYSIS != "blast" ) && ( $ANALYSIS != "kmer_analysis" ) && ( $ANALYSIS != "summarise" )  ]] ; then
          echo "analysis must be one of demultiplex, trim , format, blast, summarise , clean) "
       else
          break
@@ -226,73 +235,15 @@ please give which analysis you want (all, demultiplex, trim, format, blast, summ
    get_input_files
 
 
-   if [[ ( "$ANALYSIS" == "all" ) || ( "$ANALYSIS" == "demultiplex" ) ]]; then
-      ls $OUT_ROOT/*.demultiplexed/* > /dev/null 2>&1
-      if [ $? == 0 ] ; then
-         echo "found existing results under $OUT_ROOT/*.demultiplexed/* - are you sure you want to continue (e.g. complete an interrupted run) ? (y/n)"
-         read_answer_with_default n
-         if [[ ( $answer != "y" )  && ( $answer != "Y" ) ]]; then
-            echo "ok quitting - please either use a different output folder or clean up $OUT_ROOT/*.demultiplexed"
-            exit 1
-         fi
+   ls $OUT_ROOT/*.demultiplexed/*  $OUT_ROOT/trimming/*  $OUT_ROOT/fasta/* $OUT_ROOT/blast/* $OUT_ROOT/summary/* $OUT_ROOT/kmer_ananlysis/* > /dev/null 2>&1
+   if [ $? == 0 ] ; then
+      echo "found some existing results under $OUT_ROOT - are you sure you want to continue (e.g. complete an interrupted run) ? (y/n)"
+      read_answer_with_default n
+      if [[ ( $answer != "y" )  && ( $answer != "Y" ) ]]; then
+         echo "ok quitting - please either use a different output folder or clean up $OUT_ROOT"
+         exit 1
       fi
    fi
-   if [[ ( "$ANALYSIS" == "all" ) || ( "$ANALYSIS" == "trim" ) ]]; then
-      ls $OUT_ROOT/trimming/* > /dev/null 2>&1
-      if [ $? == 0 ] ; then
-         echo "found existing results under $OUT_ROOT/trimming - are you sure you want to continue (e.g. complete an interrupted run) ? (y/n)"
-         read_answer_with_default n
-         if [[ ( $answer != "y" )  && ( $answer != "Y" ) ]]; then
-            echo "ok quitting - please use a different output folder"
-            exit 1
-         fi
-      fi
-   fi
-   if [[ ( "$ANALYSIS" == "all" ) || ( "$ANALYSIS" == "format" ) ]]; then
-      ls $OUT_ROOT/fasta/* > /dev/null 2>&1
-      if [ $? == 0 ] ; then
-         echo "found existing results under $OUT_ROOT/fasta - are you sure you want to continue (e.g. complete an interrupted run) ? (y/n)"
-         read_answer_with_default n
-         if [[ ( $answer != "y" )  && ( $answer != "Y" ) ]]; then
-            echo "ok quitting - please use a different output folder"
-            exit 1
-         fi
-      fi
-   fi
-   if [[ ( "$ANALYSIS" == "all" ) || ( "$ANALYSIS" == "blast" ) ]]; then
-      ls $OUT_ROOT/blast/* > /dev/null 2>&1
-      if [ $? == 0 ] ; then
-         echo "found existing results under $OUT_ROOT/blast - are you sure you want to continue (e.g. complete an interrupted run) ? (y/n)"
-         read_answer_with_default n
-         if [[ ( $answer != "y" )  && ( $answer != "Y" ) ]]; then
-            echo "ok quitting - please use a different output folder"
-            exit 1
-         fi
-      fi
-   fi
-   if [[ ( "$ANALYSIS" == "all" ) || ( "$ANALYSIS" == "summarise" ) ]]; then
-      ls $OUT_ROOT/summary/* > /dev/null 2>&1
-      if [ $? == 0 ] ; then
-         echo "found existing results under $OUT_ROOT/summary - are you sure you want to continue (e.g. complete an interrupted run) ? (y/n)"
-         read_answer_with_default n
-         if [[ ( $answer != "y" )  && ( $answer != "Y" ) ]]; then
-            echo "ok quitting - please use a different output folder"
-            exit 1
-         fi
-      fi
-   fi
-   if [[ ( "$ANALYSIS" == "all" ) || ( "$ANALYSIS" == "kmer_analysis" ) ]]; then
-      ls $OUT_ROOT/kmer_ananlysis/* > /dev/null 2>&1
-      if [ $? == 0 ] ; then
-         echo "found existing results under $OUT_ROOT/kmer_analysis - are you sure you want to continue (e.g. complete an interrupted run) ? (y/n)"
-         read_answer_with_default n
-         if [[ ( $answer != "y" )  && ( $answer != "Y" ) ]]; then
-            echo "ok quitting - please use a different output folder"
-            exit 1
-         fi
-      fi
-   fi
-
 
    ####### get and check the blast data to use 
    if [[ ( $ANALYSIS == "all" ) || ( $ANALYSIS == "blast" ) ]]; then
@@ -399,9 +350,7 @@ if [ \$? != 0 ]; then
    echo \"demultiplex returned an error code ( \$? )\"
    exit 1
 fi
-if [ $ANALYSIS == \"all\" ] ; then
    ls $OUT_ROOT/*.demultiplexed/*.fastq > $OUT_ROOT/input_file_list.txt
-fi
 " >> $OUT_ROOT/run_melseq_analysis.src
    fi
 
@@ -409,14 +358,12 @@ fi
    if [[ ( $ANALYSIS == "all" ) || ( $ANALYSIS == "trim" ) ]]; then
       echo "
 mv $OUT_ROOT/input_file_list.txt $OUT_ROOT/trim_input_file_list.txt
-$GBS_PRISM_BIN/melseq_prism.sh -a trim -m $SEQLENGTH_MIN -q $SEQQUAL_MIN -O $OUT_ROOT \`cat $OUT_ROOT/trim_input_file_list.txt\` > $OUT_ROOT/trim.log 2>&1
+$MELSEQ_PRISM_BIN/melseq_prism.sh -a trim -m $SEQLENGTH_MIN -q $SEQQUAL_MIN -O $OUT_ROOT \`cat $OUT_ROOT/trim_input_file_list.txt\` > $OUT_ROOT/trim.log 2>&1
 if [ \$? != 0 ]; then
    echo \"trim returned an error code ( \$? )\"
    exit 1
 fi
-if [ $ANALYSIS == \"all\" ] ; then
    ls $OUT_ROOT/trimming/*.fastq.gz > $OUT_ROOT/input_file_list.txt
-fi
 " >> $OUT_ROOT/run_melseq_analysis.src
    fi
 
@@ -424,15 +371,13 @@ fi
    if [[ ( $ANALYSIS == "all" ) || ( $ANALYSIS == "format" ) ]]; then
       echo "
 mv $OUT_ROOT/input_file_list.txt $OUT_ROOT/format_input_file_list.txt
-$GBS_PRISM_BIN/melseq_prism.sh -a format -O $OUT_ROOT \`cat $OUT_ROOT/format_input_file_list.txt\` > $OUT_ROOT/format.log 2>&1
+$MELSEQ_PRISM_BIN/melseq_prism.sh -a format -O $OUT_ROOT \`cat $OUT_ROOT/format_input_file_list.txt\` > $OUT_ROOT/format.log 2>&1
 if [ \$? != 0 ]; then
    echo \"format returned an error code ( \$? )\"
    exit 1
 fi
-if [ $ANALYSIS == \"all\" ] ; then
    ls $OUT_ROOT/fasta/*.non-redundant.fasta > $OUT_ROOT/input_file_list.txt
    ls $OUT_ROOT/fasta/*.non-redundant.fasta > $OUT_ROOT/kmer_input_file_list.txt
-fi
 " >> $OUT_ROOT/run_melseq_analysis.src
    fi
 
@@ -440,22 +385,20 @@ fi
    if [[ ( $ANALYSIS == "all" ) || ( $ANALYSIS == "blast" ) ]]; then
       echo "
 mv $OUT_ROOT/input_file_list.txt $OUT_ROOT/blast_input_file_list.txt
-$GBS_PRISM_BIN/melseq_prism.sh -a blast -s $SIMILARITY -b $BLAST_DATABASE -O $OUT_ROOT \`cat $OUT_ROOT/blast_input_file_list.txt\` > $OUT_ROOT/blast.log 2>&1
+$MELSEQ_PRISM_BIN/melseq_prism.sh -a blast -s $SIMILARITY -b $BLAST_DATABASE -O $OUT_ROOT \`cat $OUT_ROOT/blast_input_file_list.txt\` > $OUT_ROOT/blast.log 2>&1
 if [ \$? != 0 ]; then
    echo \"blast returned an error code ( \$? )\"
    exit 1
 fi
-if [ $ANALYSIS == \"all\" ] ; then
    ls $OUT_ROOT/blast/*.results.gz > $OUT_ROOT/input_file_list.txt
-fi
 " >> $OUT_ROOT/run_melseq_analysis.src
    fi
 
    ############# summary   ##################
-   if [[ ( $ANALYSIS == "all" ) || ( $ANALYSIS == "summarise" ) ]]; then
+   if [[ ( $ANALYSIS == "all" ) || ( $ANALYSIS == "summarise" ) || ( $ANALYSIS == "blast" ) ]]; then
       echo "
 mv $OUT_ROOT/input_file_list.txt $OUT_ROOT/summarise_input_file_list.txt
-$GBS_PRISM_BIN/melseq_prism.sh -a summarise \`cat $OUT_ROOT/summarise_input_file_list.txt\` > $OUT_ROOT/summarise.log 2>&1
+$MELSEQ_PRISM_BIN/melseq_prism.sh -a summarise -O $OUT_ROOT \`cat $OUT_ROOT/summarise_input_file_list.txt\` > $OUT_ROOT/summarise.log 2>&1
 if [ \$? != 0 ]; then
    echo \"summarie returned an error code ( \$? )\"
    exit 1
@@ -469,35 +412,16 @@ fi
          echo "
 mv $OUT_ROOT/kmer_input_file_list.txt $OUT_ROOT/input_file_list.txt
 " >> $OUT_ROOT/run_melseq_analysis.src
+      fi
       echo "
 mv $OUT_ROOT/input_file_list.txt $OUT_ROOT/kmer_input_file_list.txt
-$GBS_PRISM_BIN/melseq_prism.sh -a kmer_analysis  \`cat $OUT_ROOT/blast_input_file_list.txt\` > $OUT_ROOT/kmer_analysis.log 2>&1
+$MELSEQ_PRISM_BIN/melseq_prism.sh -a kmer_analysis  -O $OUT_ROOT \`cat $OUT_ROOT/blast_input_file_list.txt\` > $OUT_ROOT/kmer_analysis.log 2>&1
 if [ \$? != 0 ]; then
    echo \"kmer_analysis returned an error code ( \$? )\"
    exit 1
 fi
 " >> $OUT_ROOT/run_melseq_analysis.src
    fi
-
-
-x="
-
-#time $MELSEQ_PRISM_BIN/melseq_prism.sh  -a trim -b /dataset/GBS_Rumen_Metagenomes/scratch/blast_analysis/GenusPlusQuinella -O $OUT_DIR $OUT_DIR/*.demultiplexed/*.fastq > $OUT_DIR/test_trim.log 2>&1
-
-#time $MELSEQ_PRISM_BIN/melseq_prism.sh  -a format -b /dataset/GBS_Rumen_Metagenomes/scratch/blast_analysis/GenusPlusQuinella -O $OUT_DIR $OUT_DIR/trimming/*.fastq.gz > $OUT_DIR/test_format.log 2>&1
-
-#time $MELSEQ_PRISM_BIN/melseq_prism.sh  -a blast -b /dataset/GBS_Rumen_Metagenomes/scratch/blast_analysis/GenusPlusQuinella -O $OUT_DIR $OUT_DIR/fasta/*.non-redundant.fasta > $OUT_DIR/test_blast.log 2>&1
-
-#time $MELSEQ_PRISM_BIN/melseq_prism.sh  -a summarise -b /dataset/GBS_Rumen_Metagenomes/scratch/blast_analysis/GenusPlusQuinella -O $OUT_DIR $OUT_DIR/blast/*.results.gz > $OUT_DIR/test_summary.log 2>&1
-
-#time $MELSEQ_PRISM_BIN/melseq_prism.sh  -a kmer_analysis  -b /dataset/GBS_Rumen_Metagenomes/scratch/blast_analysis/GenusPlusQuinella -O $OUT_DIR $OUT_DIR/fasta/*.non-redundant.fasta > $OUT_DIR/test_kmer.log 2>&1
-
-#time $MELSEQ_PRISM_BIN/melseq_prism.sh  -a blast -b /dataset/GBS_Rumen_Metagenomes/scratch/blast_analysis/GenusPlusQuinella -O $OUT_DIR /bifo/active/GBS_Rumen_Metagenomes/OLW/02_FastaSeqs/*_toBLAST.fa  > $OUT_DIR/blast.log 2>&1
-
-#time $MELSEQ_PRISM_BIN/melseq_prism.sh  -a summarise -b /dataset/GBS_Rumen_Metagenomes/scratch/blast_analysis/GenusPlusQuinella -O $OUT_DIR $OUT_DIR/blast/*.results.gz > $OUT_DIR/test_summary.log 2>&1
-
-#time $MELSEQ_PRISM_BIN/melseq_prism.sh  -a kmer_analysis  -b /dataset/GBS_Rumen_Metagenomes/scratch/blast_analysis/GenusPlusQuinella -O $OUT_DIR /bifo/active/GBS_Rumen_Metagenomes/OLW/02_FastaSeqs/*_toBLAST.fa > $OUT_DIR/test_kmer.log 2>&1
-"
 
    echo "about to run $OUT_ROOT/run_melseq_analysis.src - i.e. : "
    more $OUT_ROOT/run_melseq_analysis.src
@@ -506,9 +430,7 @@ x="
    set -x
    time source $OUT_ROOT/run_melseq_analysis.src > $OUT_ROOT/run_melseq_analysis.log 2>&1
    set +x
-
 }
-
 
 get_run_opts
 run_melseq_analysis
