adding support for merging novaseq lanes

diff --git a/_run_melseq b/_run_melseq
--- a/_run_melseq
+++ b/_run_melseq
@@ -202,6 +202,8 @@ e.g.
 
 /dataset/gseq_processing/scratch/illumina/hiseq/190614_D00390_0467_ACDR6TANXX/SampleSheet/bcl2fastq/Undetermined_S0_L004_R1_001.fastq.gz
 
+/dataset/hiseq/active/fastq-link-farm/SQ1642_HCH3GDRXY_s_1_fastq.txt.gz
+
 "
       read_answer_with_default restarting 
       if [ "$answer" != "restarting"  ]; then 
@@ -597,10 +599,26 @@ if [ \$? != 0 ]; then
    echo \"format returned an error code ( \$? )\"
    exit 1
 fi
-   ls $OUT_ROOT/fasta/*.non-redundant.fasta > $OUT_ROOT/blast_input_file_list.txt
-   ls $OUT_ROOT/fasta/*.non-redundant.fasta > $OUT_ROOT/kmer_input_file_list.txt
+   ls $OUT_ROOT/fasta/*.non-redundant.fasta > $OUT_ROOT/merge_lanes_input_file_list.txt
 " > $OUT_ROOT/${project_moniker}.run_format.sh
    chmod +x $OUT_ROOT/${project_moniker}.run_format.sh
+
+
+   ############# merge lanes ##################
+   echo "
+export SEQ_PRISMS_BIN=$SEQ_PRISMS_BIN
+export MELSEQ_PRISM_BIN=$MELSEQ_PRISM_BIN
+export GBS_PRISM_BIN=$GBS_PRISM_BIN
+
+$MELSEQ_PRISM_BIN/melseq_prism.sh -C $HPC_TYPE -a merge_lanes -O $OUT_ROOT \`cat $OUT_ROOT/merge_lanes_input_file_list.txt\` > $OUT_ROOT/run_merge_lanes.log 2>&1
+if [ \$? != 0 ]; then
+   echo \"format returned an error code ( \$? )\"
+   exit 1
+fi
+   ls $OUT_ROOT/merged_fasta/*.non-redundant.fasta  > $OUT_ROOT/blast_input_file_list.txt
+   ls $OUT_ROOT/merged_fasta/*.non-redundant.fasta  > $OUT_ROOT/kmer_input_file_list.txt
+" > $OUT_ROOT/${project_moniker}.run_merge_lanes.sh
+   chmod +x $OUT_ROOT/${project_moniker}.run_merge_lanes.sh
 
 
    ############# blast   ##################
